[package]
name = "bevy-trait-query"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "concrete"
harness = false

[[bench]]
name = "universal"
harness = false

[[bench]]
name = "existential"
harness = false

[[bench]]
name = "fragmented"
harness = false
